document.querySelector('ul.list').addEventListener('click', function (e) {

    var target = e.target.nodeName == 'A' ? $(e.target).text() : $(e.target).find('a').text()

    $('.detail p.content').html("<p class='number'>" + target + "</p>" + lorem);
    $('.detail').animate({scrollTop: '0px'}, 200);

})

var lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Porta nibh venenatis cras sed felis eget velit aliquet sagittis. Ut diam quam nulla porttitor massa. Nisl purus in mollis nunc sed id semper risus. Augue lacus viverra vitae congue eu consequat. Lacus vestibulum sed arcu non odio. Blandit cursus risus at ultrices. Diam phasellus vestibulum lorem sed risus ultricies tristique. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Tellus molestie nunc non blandit massa enim nec dui. Sem nulla pharetra diam sit amet. Consequat nisl vel pretium lectus quam id leo. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Et pharetra pharetra massa massa. Nibh tellus molestie nunc non blandit massa enim. Quis viverra nibh cras pulvinar mattis nunc. Quam lacus suspendisse faucibus interdum posuere lorem.
Vulputate ut pharetra sit amet aliquam id diam. Tortor consequat id porta nibh. Accumsan lacus vel facilisis volutpat est velit egestas. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Mauris augue neque gravida in fermentum et sollicitudin ac. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Sit amet facilisis magna etiam. Elit at imperdiet dui accumsan sit amet nulla facilisi. Vitae semper quis lectus nulla at volutpat. Orci a scelerisque purus semper eget duis at tellus at. Congue quisque egestas diam in arcu cursus euismod.

Feugiat vivamus at augue eget arcu dictum varius. Egestas tellus rutrum tellus pellentesque eu. Arcu dictum varius duis at consectetur lorem donec massa. Justo eget magna fermentum iaculis eu non. Facilisi nullam vehicula ipsum a arcu. Malesuada proin libero nunc consequat. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Elit ut aliquam purus sit amet luctus. Accumsan sit amet nulla facilisi morbi. Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis.

Egestas dui id ornare arcu. Vitae tempus quam pellentesque nec nam. Vulputate mi sit amet mauris commodo. Suspendisse ultrices gravida dictum fusce ut placerat orci. Nec ullamcorper sit amet risus nullam. Nisl suscipit adipiscing bibendum est. Sapien nec sagittis aliquam malesuada bibendum. Aliquet bibendum enim facilisis gravida neque convallis a. Eu lobortis elementum nibh tellus molestie nunc. Tempus iaculis urna id volutpat. Purus gravida quis blandit turpis cursus in hac habitasse. Eu lobortis elementum nibh tellus. Ut ornare lectus sit amet est placerat in egestas. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Tellus rutrum tellus pellentesque eu tincidunt. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Praesent tristique magna sit amet purus gravida quis blandit turpis.

Mattis enim ut tellus elementum sagittis. Commodo nulla facilisi nullam vehicula ipsum a. Placerat duis ultricies lacus sed turpis tincidunt id. Est sit amet facilisis magna etiam tempor orci. Lacus sed turpis tincidunt id aliquet risus feugiat in. Viverra maecenas accumsan lacus vel facilisis volutpat est velit egestas. Nullam vehicula ipsum a arcu. Aliquam ultrices sagittis orci a scelerisque purus semper. Mi in nulla posuere sollicitudin aliquam ultrices. Proin fermentum leo vel orci porta non pulvinar neque. Lacus luctus accumsan tortor posuere. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. Magna eget est lorem ipsum dolor sit amet. Pharetra diam sit amet nisl suscipit adipiscing bibendum.

Elementum integer enim neque volutpat ac. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Maecenas sed enim ut sem viverra. Egestas sed tempus urna et. Tincidunt eget nullam non nisi est sit amet facilisis magna. Pharetra magna ac placerat vestibulum lectus mauris. Nunc sed id semper risus in hendrerit gravida rutrum quisque. Posuere sollicitudin aliquam ultrices sagittis orci a. Tempor orci dapibus ultrices in iaculis nunc sed. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Vel quam elementum pulvinar etiam non quam. Mi bibendum neque egestas congue quisque egestas diam in arcu. Est ante in nibh mauris cursus mattis molestie. Accumsan sit amet nulla facilisi morbi tempus. Facilisis mauris sit amet massa vitae tortor. Amet dictum sit amet justo donec enim diam. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra.

Eget arcu dictum varius duis at consectetur. Fermentum iaculis eu non diam phasellus vestibulum lorem sed risus. Egestas dui id ornare arcu odio. Varius morbi enim nunc faucibus a pellentesque. Velit laoreet id donec ultrices tincidunt arcu non. Fringilla ut morbi tincidunt augue interdum velit euismod. A pellentesque sit amet porttitor eget. Felis eget nunc lobortis mattis aliquam faucibus. Eget sit amet tellus cras adipiscing enim. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Arcu cursus vitae congue mauris rhoncus aenean. Tincidunt nunc pulvinar sapien et ligula. Elementum sagittis vitae et leo duis. At augue eget arcu dictum varius duis. Gravida quis blandit turpis cursus in. Libero enim sed faucibus turpis.

Magna ac placerat vestibulum lectus. Amet consectetur adipiscing elit duis tristique sollicitudin. Ut etiam sit amet nisl purus in mollis nunc. Arcu dui vivamus arcu felis bibendum ut. Vitae tortor condimentum lacinia quis vel eros donec ac. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Cursus vitae congue mauris rhoncus aenean vel elit. Amet aliquam id diam maecenas ultricies mi eget. Lacus vestibulum sed arcu non odio euismod lacinia. Vel pretium lectus quam id leo in. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Sollicitudin ac orci phasellus egestas. Interdum consectetur libero id faucibus nisl tincidunt. Id semper risus in hendrerit gravida rutrum quisque. Felis bibendum ut tristique et egestas quis ipsum. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Orci nulla pellentesque dignissim enim. Dolor magna eget est lorem ipsum dolor. Vitae et leo duis ut diam.

Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Scelerisque eleifend donec pretium vulputate. Fringilla phasellus faucibus scelerisque eleifend donec. Imperdiet dui accumsan sit amet nulla facilisi. Adipiscing commodo elit at imperdiet dui. Pellentesque nec nam aliquam sem et tortor consequat. Fusce ut placerat orci nulla. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Vestibulum mattis ullamcorper velit sed ullamcorper. Orci a scelerisque purus semper. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Quis blandit turpis cursus in hac. Id donec ultrices tincidunt arcu non. Bibendum est ultricies integer quis auctor elit sed vulputate. Elementum curabitur vitae nunc sed velit. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Ut enim blandit volutpat maecenas volutpat blandit aliquam. Nisi lacus sed viverra tellus in hac.

Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Varius sit amet mattis vulputate enim nulla aliquet. Nunc sed velit dignissim sodales ut. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Commodo sed egestas egestas fringilla phasellus faucibus. Orci ac auctor augue mauris augue. Mattis enim ut tellus elementum sagittis vitae et leo. Fermentum posuere urna nec tincidunt. Molestie at elementum eu facilisis sed odio morbi quis. Gravida in fermentum et sollicitudin. Urna cursus eget nunc scelerisque viverra mauris in. Dolor sit amet consectetur adipiscing elit duis. Laoreet sit amet cursus sit amet dictum sit amet justo. Quam elementum pulvinar etiam non quam lacus. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Scelerisque in dictum non consectetur.

Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Magna etiam tempor orci eu lobortis. Non blandit massa enim nec dui nunc mattis enim. Quis eleifend quam adipiscing vitae proin. Risus in hendrerit gravida rutrum quisque non tellus orci. Ut etiam sit amet nisl purus in mollis nunc sed. Auctor neque vitae tempus quam pellentesque nec. Turpis in eu mi bibendum neque egestas congue quisque egestas. Gravida rutrum quisque non tellus. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Non enim praesent elementum facilisis leo vel fringilla.

Faucibus turpis in eu mi bibendum neque egestas congue. Pretium lectus quam id leo in vitae turpis. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Consequat interdum varius sit amet mattis vulputate. Ultrices vitae auctor eu augue. Diam sit amet nisl suscipit. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Amet volutpat consequat mauris nunc. Id velit ut tortor pretium viverra suspendisse potenti nullam. Cursus euismod quis viverra nibh. Dui vivamus arcu felis bibendum ut. Turpis massa tincidunt dui ut ornare lectus sit amet est. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Dui sapien eget mi proin sed libero enim sed. Integer eget aliquet nibh praesent tristique magna sit amet.

Integer vitae justo eget magna fermentum iaculis. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Turpis in eu mi bibendum neque egestas congue. Venenatis cras sed felis eget velit. Porta nibh venenatis cras sed felis eget. Iaculis eu non diam phasellus vestibulum lorem. Malesuada nunc vel risus commodo viverra maecenas accumsan. Mi sit amet mauris commodo quis imperdiet. Interdum velit euismod in pellentesque massa placerat duis ultricies lacus. Leo vel orci porta non pulvinar neque laoreet. Tincidunt tortor aliquam nulla facilisi. Sem integer vitae justo eget magna fermentum iaculis. Consectetur purus ut faucibus pulvinar elementum integer. Euismod lacinia at quis risus sed. Nibh sit amet commodo nulla facilisi nullam vehicula. Lorem ipsum dolor sit amet consectetur adipiscing elit. Lorem sed risus ultricies tristique. Ipsum dolor sit amet consectetur adipiscing elit ut.

Rhoncus mattis rhoncus urna neque viverra justo nec. Augue neque gravida in fermentum et sollicitudin ac orci. Tristique magna sit amet purus gravida quis blandit turpis. Pellentesque id nibh tortor id aliquet. Lacinia quis vel eros donec ac odio tempor orci. Consectetur libero id faucibus nisl. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Pharetra vel turpis nunc eget lorem dolor sed viverra. Habitasse platea dictumst vestibulum rhoncus. Libero enim sed faucibus turpis.

Mattis nunc sed blandit libero volutpat. Aliquam vestibulum morbi blandit cursus risus. Molestie nunc non blandit massa enim nec dui nunc mattis. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Viverra aliquet eget sit amet. Et pharetra pharetra massa massa ultricies mi. Sem nulla pharetra diam sit amet. Eu scelerisque felis imperdiet proin fermentum. Aliquam purus sit amet luctus venenatis lectus. Faucibus in ornare quam viverra orci sagittis. Congue mauris rhoncus aenean vel. Senectus et netus et malesuada fames. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Senectus et netus et malesuada fames ac turpis egestas sed. A arcu cursus vitae congue mauris rhoncus.`
